import * as Blockly from 'blockly/core';

export const BLOCK_TYPES = {
  MOVE_FORWARD: 'move_forward',
  MOVE_BACKWARD: 'move_backward',
  TURN_LEFT: 'turn_left',
  TURN_RIGHT: 'turn_right',
  STOP: 'stop',
  BRAKE: 'brake',
  CLAW_OPEN: 'claw_open',
  CLAW_CLOSE: 'claw_close',
  WAIT_SECONDS: 'wait_seconds',
  WAIT_MILLIS: 'wait_millis',
  SET_SPEED: 'set_speed',
  CHANGE_SPEED: 'change_speed',
  GET_SPEED: 'get_speed',
} as const;

export function defineBeetleBotBlocks() {
  Blockly.defineBlocksWithJsonArray([
    {
      type: BLOCK_TYPES.MOVE_FORWARD,
      message0: 'forward',
      previousStatement: null,
      nextStatement: null,
      colour: '#ff6b35',
      tooltip: 'Move forward',
    },
    {
      type: BLOCK_TYPES.MOVE_BACKWARD,
      message0: 'backward',
      previousStatement: null,
      nextStatement: null,
      colour: '#ff6b35',
      tooltip: 'Move backward',
    },
    {
      type: BLOCK_TYPES.TURN_LEFT,
      message0: 'turn left',
      previousStatement: null,
      nextStatement: null,
      colour: '#ff6b35',
      tooltip: 'Turn left',
    },
    {
      type: BLOCK_TYPES.TURN_RIGHT,
      message0: 'turn right',
      previousStatement: null,
      nextStatement: null,
      colour: '#ff6b35',
      tooltip: 'Turn right',
    },
    {
      type: BLOCK_TYPES.STOP,
      message0: 'stop',
      previousStatement: null,
      nextStatement: null,
      colour: '#f44336',
      tooltip: 'Stop motors',
    },
    {
      type: BLOCK_TYPES.BRAKE,
      message0: 'brake',
      previousStatement: null,
      nextStatement: null,
      colour: '#f44336',
      tooltip: 'Active brake',
    },
    {
      type: BLOCK_TYPES.CLAW_OPEN,
      message0: 'open claw',
      previousStatement: null,
      nextStatement: null,
      colour: '#ff9800',
      tooltip: 'Open claw',
    },
    {
      type: BLOCK_TYPES.CLAW_CLOSE,
      message0: 'close claw',
      previousStatement: null,
      nextStatement: null,
      colour: '#ff9800',
      tooltip: 'Close claw',
    },
    {
      type: BLOCK_TYPES.WAIT_SECONDS,
      message0: 'wait %1 s',
      args0: [{
        type: 'input_value',
        name: 'SECONDS',
        check: 'Number',
      }],
      previousStatement: null,
      nextStatement: null,
      colour: '#888888',
      tooltip: 'Wait seconds',
    },
    {
      type: BLOCK_TYPES.WAIT_MILLIS,
      message0: 'wait %1 ms',
      args0: [{
        type: 'input_value',
        name: 'MILLIS',
        check: 'Number',
      }],
      previousStatement: null,
      nextStatement: null,
      colour: '#888888',
      tooltip: 'Wait milliseconds',
    },
    {
      type: BLOCK_TYPES.SET_SPEED,
      message0: 'speed = %1',
      args0: [{
        type: 'input_value',
        name: 'SPEED',
        check: 'Number',
      }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2196f3',
      tooltip: 'Set speed 60-255',
    },
    {
      type: BLOCK_TYPES.CHANGE_SPEED,
      message0: 'speed += %1',
      args0: [{
        type: 'input_value',
        name: 'DELTA',
        check: 'Number',
      }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2196f3',
      tooltip: 'Change speed',
    },
    {
      type: BLOCK_TYPES.GET_SPEED,
      message0: 'speed',
      output: 'Number',
      colour: '#2196f3',
      tooltip: 'Current speed',
    },
  ]);
}